import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
	index('routes/home.tsx'),
	route('services', 'routes/services.tsx'),
	route('services/:slug', 'routes/services.$slug.tsx'),
	route('solutions', 'routes/solutions.tsx'),
	route('solutions/:slug', 'routes/solutions.$slug.tsx'),
	route('industries', 'routes/industries.tsx'),
	route('industries/:slug', 'routes/industries.$slug.tsx'),
	route('work', 'routes/work.tsx'),
	route('work/:slug', 'routes/work.$slug.tsx'),
	route('company', 'routes/company.tsx'),
	route('company/why-codelaro', 'routes/company.why-codelaro.tsx'),
	route('company/process', 'routes/company.process.tsx'),
	route('company/careers', 'routes/company.careers.tsx'),
	route('insights', 'routes/insights.tsx'),
	route('contact', 'routes/contact.tsx'),
	route('start-a-project', 'routes/start-a-project.tsx'),
	route('book-a-consultation', 'routes/book-a-consultation.tsx'),
	route('faq', 'routes/faq.tsx'),
	route('privacy-policy', 'routes/privacy-policy.tsx'),
	route('terms', 'routes/terms.tsx'),
	route('cookie-policy', 'routes/cookie-policy.tsx'),
	route('accessibility', 'routes/accessibility.tsx'),
	route('thank-you', 'routes/thank-you.tsx'),
	route('*', 'routes/$.tsx'),
	route('sitemap.xml', 'routes/sitemap.xml.ts'),
	route('robots.txt', 'routes/robots.txt.ts'),
	route('api/health', 'routes/api.health.ts'),
	route('api/*', 'routes/api.$.ts'),
] satisfies RouteConfig;
